### ISSUE TITLE
node 10 Invalid typed array length

### ISSUE THREAD

**Issue by LarsDenBakker** [guybedford/es-module-lexer#14]
I'm testing  a large variety of packages. On node 10 I'm getting these kinds of errors:

```
RangeError: Invalid typed array length: 86449
    at new Uint32Array (<anonymous>)
    at /Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/es-module-lexer/dist/lexer.cjs.js:12:11
    at parse (/Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/es-module-lexer/dist/lexer.cjs.js:19:4)
    at resolveModuleImports (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/es-dev-server/dist/utils/resolve-module-imports.js:180:48)
    at compileMiddleware (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/es-dev-server/dist/middleware/compile-middleware.js:138:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The errors are for lengths such as 86449, 534408, 14579, 30011, 95552.

Files which are failing:
- https://unpkg.com/chai@4.2.0/chai.js
- https://unpkg.com/sinon@7.4.1/pkg/sinon-esm.js
- https://unpkg.com/underscore@1.9.1/underscore.js
- https://unpkg.com/react@16.9.0/umd/react.development.js
- https://unpkg.com/rollup@1.19.4/dist/rollup.browser.es.js

It doesn't seem to be throwing errors on node 12. I'm trying to find out what's causing this, maybe you have am idea?

**Comment by guybedford** [comment]
I've just implemented the encoding change to UTF16 in https://github.com/guybedford/es-module-lexer/pull/15.

Just publishing a release now - if you could test against that, I expect that will likely have resolved the issue but let me know if not too.

**Comment by LarsDenBakker** [comment]
Unfortunately, it's still giving me errors :(

```
RangeError: Invalid typed array length: 345752
    at new Uint16Array (<anonymous>)
    at parse (/Users/larsdenbakker/Workspace/code/private/open-wc/node_modules/es-module-lexer/dist/lexer.cjs:1:226)
    at resolveModuleImports (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/es-dev-server/dist/utils/resolve-module-imports.js:180:48)
    at compileMiddleware (/Users/larsdenbakker/Workspace/code/private/open-wc/packages/es-dev-server/dist/middleware/compile-middleware.js:138:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by guybedford** [comment]
Does it happen reproducibly and always on the first attempt? Or does it take a few sources before you hit this?

**Comment by LarsDenBakker** [comment]
It's reproducible on the first try, I made https://github.com/guybedford/es-module-lexer/pull/16 with a minimal setup

**Comment by guybedford** [comment]
Fixed in https://github.com/guybedford/es-module-lexer/commit/46f9e907f5590d28a12637d5e1503a34a1fffac4.

**Comment by LarsDenBakker** [comment]
Thanks, it works fine now!
